### ISSUE TITLE
Get on PyPI

### ISSUE THREAD

**Issue by kaftand** [kaftand/quantregpy#10]

**Comment by paulkaefer** [comment]
@kaftand if you go to [the actions tab](https://github.com/kaftand/quantregpy/actions) and click "New workflow", there's a sample that will `Publish a Python Package to PyPI on release.` We might want to see what we need for the bare minimum configuration, and actually set this up now. Even if we have a bare-bones package, getting on PyPI will be helpful for development and attracting other contributors.
