### ISSUE TITLE
add documentation for build & specifically compiling Fortran

### ISSUE THREAD

**Issue by paulkaefer** [kaftand/quantregpy#5]
I'm getting this:
```bash
...
Could not locate executable g95
customize PGroupFCompiler
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
warning: build_ext: f77_compiler=None is not available.

building 'rqf' extension
error: extension 'rqf' has Fortran sources but no Fortran compiler found
```
...and a lot of `Could not locate...` prior. Could you tell me what steps you used and/or update the README?

**Comment by kaftand** [comment]
It looks like `numpy`'s "build from source" tutorial gives some direction: https://numpy.org/doc/stable/user/building.html
To answer your question, yes, it looks like you need a fortran compiler and it needs to be in your path.


That being said, yes, this should be added to the wiki/readme. Something else that needs to be worked on is including dependencies (maybe in setup.py? I am unsure how dependencies should be handled with python packages).

**Comment by kaftand** [comment]
I also only bring up numpy's documentation because the library we use to run python with fortran is the same that numpy uses.

**Comment by paulkaefer** [comment]
@kaftand I appear to have successfully installed it on Ubuntu. I followed [this](https://github.com/CamDavidsonPilon/lifelines/issues/80) to `apt-get install python-dev` (I can add this to the README if your build fails searching for `Python.h`).

However, now I'm getting:
```Python
>>> from quantregpy.quantreg import rq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/Programming/python/quantregpy/quantregpy/__init__.py", line 1, in <module>
    import rqf
ImportError: No module named 'rqf'
```

Any ideas? [Doesn't seem](https://pypi.org/search/?q=rqf) to be a package to `pip install`...

**Comment by paulkaefer** [comment]
Ah, I have success if I run from `build/lib.linux-x86_64-3.4`...

**Comment by paulkaefer** [comment]
Must be running Python 3.6+

**Comment by kaftand** [comment]
We should probably make this easier to collaborate. Numpy uses virtualenv. I'm thinking anaconda would be nice, since I atleast have a little experience with that. Here is what numpy does: https://numpy.org/devdocs/dev/development_environment.html.

**Comment by paulkaefer** [comment]
Good idea. I will try to look at this tonight more, but if you have time, go for it!

**Comment by kaftand** [comment]
Closing this issue because I broke it into 3 smaller issues: #6 #7 and #8
