### ISSUE TITLE
Research CI/CD

### ISSUE THREAD

**Issue by kaftand** [kaftand/quantregpy#9]

**Comment by paulkaefer** [comment]
There are quite a few sample actions, including one to run tests: see [here](https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions) for more details.

I added one to run linting on every push... it seems to be erring, but let's give it a few more pushes to see what happens.

**Comment by paulkaefer** [comment]
As I mentioned, I attended a neat presentation on CI/CD. In summary, I'm convinced that at least the needs as of right now can be done using GitHub actions. We could easily have it perform linting, and run arbitrary tests that we develop. We can investigate further if we have needs beyond what's offered for free.
